schema = {
  "name": "objects",
  "fields": [

# These copied from the LSST diaObject
# https://sdm-schemas.lsst.io/apdb.html

{"section":"Basic information", "doc":"ID, position, proper motion"},
    {"name": "diaObjectId",        "type": "long",   "doc": "ID for this object", "extra": "NOT NULL" },
    {"name": "ra",                 "type": "double", "doc": "Mean RA of this object" },
    {"name": "decl",               "type": "double", "doc": "Mean Dec of this object"},
    {"name": "pmRa",               "type":"float",   "doc":"Proper motion in right ascension (mas/yr)"},
    {"name": "pmDec",              "type":"float",   "doc":"Proper motion in declination (mas/yr)"},

{"section":"Lightcurve interval", "doc":"MJD of the first and last diaSource of this diaObject"},
    {"name":  "lastDiaSourceMJD", "type": "double", "doc": "Latest MJD of a diaSource" },
    {"name": "firstDiaSourceMJD", "type": "double", "doc": "Earliest MJD of a diaSource" },

{"section":"Latest Flux", "doc":"Most recent fluxes with errors"},
    {"name":"u_psfFlux", "type":"float", "doc":"Latest u flux (nJy)"},
{"name":"u_psfFluxMean", "type":"float", "doc":"Weighted mean point-source model magnitude for u filter. (nJy)"},
{"name":"u_psfFluxMeanErr", "type":"float", "doc":"Standard error of u_psfFluxMean. (nJy)"},

    {"name":"g_psfFlux", "type":"float", "doc":"Latest g flux (nJy)"},
{"name":"g_psfFluxMean", "type":"float", "doc":"Weighted mean point-source model magnitude for g filter. (nJy)"},
{"name":"g_psfFluxMeanErr", "type":"float", "doc":"Standard error of g_psfFluxMean. (nJy)"},

    {"name":"r_psfFlux", "type":"float", "doc":"Latest r flux (nJy)"},
{"name":"r_psfFluxMean", "type":"float", "doc":"Weighted mean point-source model magnitude for r filter. (nJy)"},
{"name":"r_psfFluxMeanErr", "type":"float", "doc":"Standard error of r_psfFluxMean. (nJy)"},

    {"name":"i_psfFlux", "type":"float", "doc":"Latest i flux (nJy)"},
{"name":"i_psfFluxMean", "type":"float", "doc":"Weighted mean point-source model magnitude for i filter. (nJy)"},
{"name":"i_psfFluxMeanErr", "type":"float", "doc":"Standard error of i_psfFluxMean. (nJy)"},

    {"name":"z_psfFlux", "type":"float", "doc":"Latest z flux (nJy)"},
{"name":"z_psfFluxMean", "type":"float", "doc":"Weighted mean point-source model magnitude for z filter. (nJy)"},
{"name":"z_psfFluxMeanErr", "type":"float", "doc":"Standard error of z_psfFluxMean. (nJy)"},

    {"name":"y_psfFlux", "type":"float", "doc":"Latest y flux (nJy)"},
{"name":"y_psfFluxMean", "type":"float", "doc":"Weighted mean point-source model magnitude for y filter. (nJy)"},
{"name":"y_psfFluxMeanErr", "type":"float", "doc":"Standard error of y_psfFluxMean. (nJy)"},

{"section":"Counting", "doc":"Counts of diaSources of different bands"},
    {"name": "nSources",  "type": "int", "doc": "Number of diaSources associated with this diaObject", "extra": "NOT NULL"},
    {"name": "nuSources", "type": "int", "doc": "Number of u sources" },
    {"name": "ngSources", "type": "int", "doc": "Number of g sources" },
    {"name": "nrSources", "type": "int", "doc": "Number of r sources" },
    {"name": "niSources", "type": "int", "doc": "Number of i sources" },
    {"name": "nzSources", "type": "int", "doc": "Number of z sources" },
    {"name": "nySources", "type": "int", "doc": "Number of y sources" },

{"section":"Nearest", "doc":"Nearest objects from LSST and other catalogs"},
    {"name": "nearbyExtObj1",     "type":"long",     "doc":"Id of the closest extended DR Object by second moment-based separation."},
    {"name": "nearbyExtObj1Sep",  "type":"float",    "doc":"Second moment-based separation of nearbyExtObj1 (unitless)."},
    {"name": "nearbyObj1",        "type":"long",     "doc":"Id of the closest nearby object."},
    {"name": "nearbyObj1Dist",    "type":"float",    "doc":"Distance to nearbyObj1 (arcsec)"},
    {"name": "nearbyObj1LnP",     "type":"float",    "doc":"Natural log of the probability that the observed diaObject is the same as the nearbyObj1."},
    {"name": "nearbyLowzGal",     "type":"str",      "doc":"External catalog name of the nearest low-z potential host."},
    {"name": "nearbyLowzGalSep",  "type":"float",    "doc":"Separation distance of nearbyLowzGal. (arcsc)"},

{"section":"Absolute magnitude", "doc":"Brightness at 1 parsec"},
    {"name": "absMag", "type": "float", "doc":"Brightest peak absolute magnitude if host galaxy with distance available"},

# https://roywilliams.github.io/papers/Bazin_Exp_Blackbody.pdf
{"section":"BazinBlackBody (BBB)", "doc":"Lightcurve fit as Bazin or Exp in time, Blackbody in wavelength"},
    {"name": "BBBRiseRate", "type": "float", "doc": "Fitted Bazin or Exp rise rate" },
    {"name": "BBBFallRate", "type": "float", "doc": "Fitted Bazin fall rate or NULL if Exp" },
    {"name": "BBBTemp",     "type": "float", "doc": "Fitted Bazin temperature, kiloKelvins" },

{"section":"Milky Way", "doc":"Galactic latitude and extinction"},
    {"name": "glat", "type": "float", "doc": "Galactic latitude" },
    {"name": "ebv", "type": "float", "doc": "Extinction E(B-V) Schlegel, Finkbeiner & Davis (1998)" },

# Student t-test for change of mean brightness
{"section":"Jump detector", "doc":"Number of sigma jump from 20 day mean"},
    {"name": "jumpFromMean20", "type": "float", "doc": "Number of sigma jump of recent flux from previous 20 days"},

{"section":"Revisit colours", "doc":"Colours from 33-minute revisits"},
    {"name": "latest_rv_mjd",         "type": "float", "doc": "Latest revisit MJD" },
    {"name": "latest_rv_colour_mag",  "type": "float", "doc": "Magnitude difference from latest revisit" },
    {"name": "latest_rv_colour_bands","type": "str",   "doc": "Bands used for latest revisit colour, eg g-r, u-r" },
    {"name": "latest_rv_colour_temp", "type": "float", "doc": "Effective temperature from latest revisit, kiloKelvin" },
    {"name": "penultimate_rv_mjd",         "type": "float", "doc": "Penultimate revisit MJD" },
    {"name": "penultimate_rv_colour_mag",  "type": "float", "doc": "Magnitude difference from Penultimate revisit" },
    {"name": "penultimate_rv_colour_bands","type": "str",   "doc": "Bands used for penultimate revisit colour, eg g-r, u-r" },
    {"name": "penultimate_rv_colour_temp", "type": "float", "doc": "Effective temperature from penultimate revisit, kiloKelvin" },

{"section":"Utility", "doc":"Other attributes"},
# HTM index
    {"name": "htm16", "type": "long", "doc": "Hierarchical Triangular Mesh level 16", "extra": "NOT NULL" },
# timestamp for last modified
    {"name": "timestamp",
      "type": "timestamp",
      "extra": "DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP",
      "doc": "Time at which this object last modified"
    },
  ],
  "ext_fields": [
#{"name":"diaObjectId", "type":"long", "doc":"Unique identifier of this DiaObject. ()"},

#{"name":"decl", "type":"double", "doc":"Declination coordinate of the position of the object at time radecMjdTai. (deg)"},
{"name":"decErr", "type":"float", "doc":"Uncertainty of dec. (deg)"},
#{"name":"ra", "type":"double", "doc":"Right ascension coordinate of the position of the object at time radecMjdTai. (deg)"},
{"name":"raErr", "type":"float", "doc":"Uncertainty of ra. (deg)"},
{"name":"ra_dec_Cov", "type":"float", "doc":"Covariance between ra and dec. (deg**2)"},

#{"name":"radecMjdTai", "type":"double", "doc":"Time at which the object was at a position ra/dec ()"},

#{"name": "nearbyExtObj1",     "type":"long",     "doc":"Id of the closest extended DR Object by second moment-based separation."},
#{"name": "nearbyExtObj1Sep",  "type":"float",    "doc":"Second moment-based separation of nearbyExtObj1 (unitless)."},
#{"name": "nearbyObj1",        "type":"long",     "doc":"Id of the closest nearby object."},
#{"name": "nearbyObj1Dist",    "type":"float",    "doc":"Distance to nearbyObj1 (arcsec)"},
#{"name": "nearbyObj1LnP",     "type":"float",    "doc":"Natural log of the probability that the observed diaObject is the same as the nearbyObj1."},
#{"name": "nearbyLowzGal",     "type":"str",      "doc":"External catalog name of the nearest low-z potential host."},
#{"name": "nearbyLowzGalSep",  "type":"float",    "doc":"Separation distance of nearbyLowzGal. (arcsc)"},
#{"name":"nearbyObj1", "type":"long", "doc":"Id of the closest nearby object. ()"},

{"name":"nearbyExtObj2", "type":"long", "doc":"Id of the second closest extended DR Object by second moment-based separation. ()"},
{"name":"nearbyExtObj2Sep", "type":"float", "doc":"Second moment-based separation of nearbyExtObj2 (unitless). ()"},
{"name":"nearbyObj2", "type":"long", "doc":"Id of the second-closest nearby object. ()"},
{"name":"nearbyObj2Dist", "type":"float", "doc":"Distance to nearbyObj2. (arcsec)"},
{"name":"nearbyObj2LnP", "type":"float", "doc":"Natural log of the probability that the observed diaObject is the same as the nearbyObj2. ()"},

{"name":"nearbyExtObj3", "type":"long", "doc":"Id of the third closest extended DR Object by second moment-based separation. ()"},
{"name":"nearbyExtObj3Sep", "type":"float", "doc":"Second moment-based separation of nearbyExtObj3 (unitless). ()"},
{"name":"nearbyObj3", "type":"long", "doc":"Id of the third-closest nearby object. ()"},
{"name":"nearbyObj3Dist", "type":"float", "doc":"Distance to nearbyObj3. (arcsec)"},
{"name":"nearbyObj3LnP", "type":"float", "doc":"Natural log of the probability that the observed diaObject is the same as the nearbyObj3. ()"},

{"name":"parallax", "type":"float", "doc":"Parallax. (mas)"},
{"name":"parallaxErr", "type":"float", "doc":"Uncertainty of parallax. (mas)"},
#{"name":"pmDec", "type":"float", "doc":"Proper motion of declination. (mas/yr)"},
{"name":"pmDec_parallax_Cov", "type":"float", "doc":"Covariance of pmDec and parallax. (mas**2/yr)"},
{"name":"pmDecErr", "type":"float", "doc":"Uncertainty of pmDec. (mas/yr)"},
{"name":"pmParallaxChi2", "type":"float", "doc":"Chi^2 static of the model fit. ()"},
{"name":"pmParallaxLnL", "type":"float", "doc":"Natural log of the likelihood of the linear proper motion parallax fit. ()"},
{"name":"pmParallaxNdata", "type":"int", "doc":"The number of data points used to fit the model. ()"},
#{"name":"pmRa", "type":"float", "doc":"Proper motion in right ascension. (mas/yr)"},
{"name":"pmRa_parallax_Cov", "type":"float", "doc":"Covariance of pmRa and parallax. (mas**2/yr)"},
{"name":"pmRa_pmDec_Cov", "type":"float", "doc":"Covariance of pmRa and pmDec. (mas**2/yr**2)"},
{"name":"pmRaErr", "type":"float", "doc":"Uncertainty of pmRa. (mas/yr)"},
{"name":"radecMjdTai", "type":"double", "doc":"Time at which the object was at a position ra/dec ()"},

{"name":"validityEnd", "type":"timestamp", "doc":"Processing time when validity of this diaObject ends. ()"},
{"name":"validityStart", "type":"timestamp", "doc":"Processing time when validity of this diaObject starts. ()"},

{"name":"lastNonForcedSource", "type":"timestamp", "doc":"Last time when non-forced DIASource was seen for this object. ()"},
{"name":"nDiaSources", "type":"int", "doc":"Total number of DiaSources associated with this DiaObject. ()"},

{"name":"u_fpFluxMean", "type":"float", "doc":"Weighted mean forced photometry flux for u filter. (nJy)"},
{"name":"u_fpFluxMeanErr", "type":"float", "doc":"Standard error of u_fpFluxMean. (nJy)"},
{"name":"u_fpFluxSigma", "type":"float", "doc":"Standard deviation of the distribution of u_fpFlux. (nJy)"},
{"name":"u_psfFluxChi2", "type":"float", "doc":"Chi^2 statistic for the scatter of u_psfFlux around u_psfFluxMean. ()"},
{"name":"u_psfFluxErrMean", "type":"float", "doc":"Mean of the u band flux errors. (nJy)"},
{"name":"u_psfFluxLinearIntercept", "type":"float", "doc":"Linear best fit Intercept of the u band fluxes. ()"},
{"name":"u_psfFluxLinearSlope", "type":"float", "doc":"Linear best fit slope of the u band fluxes. (nJy/d)"},
{"name":"u_psfFluxMAD", "type":"float", "doc":"Median absolute deviation u band fluxes. (nJy)"},
{"name":"u_psfFluxMax", "type":"float", "doc":"Maximum observed u band fluxes. (nJy)"},
{"name":"u_psfFluxMaxSlope", "type":"float", "doc":"Maximum slope between u band flux obsevations max(delta_flux/delta_time). (nJy/d)"},
#{"name":"u_psfFluxMean", "type":"float", "doc":"Weighted mean point-source model magnitude for u filter. (nJy)"},
#{"name":"u_psfFluxMeanErr", "type":"float", "doc":"Standard error of u_psfFluxMean. (nJy)"},
{"name":"u_psfFluxMin", "type":"float", "doc":"Minimum observed u band fluxes. (nJy)"},
{"name":"u_psfFluxNdata", "type":"int", "doc":"The number of data points used to compute u_psfFluxChi2. ()"},
{"name":"u_psfFluxPercentile05", "type":"float", "doc":"Value at the 5% percentile of the u band fluxes. (nJy)"},
{"name":"u_psfFluxPercentile25", "type":"float", "doc":"Value at the 25% percentile of the u band fluxes. (nJy)"},
{"name":"u_psfFluxPercentile50", "type":"float", "doc":"Value at the 50% percentile (median) of the u band fluxes. (nJy)"},
{"name":"u_psfFluxPercentile75", "type":"float", "doc":"Value at the 75% percentile of the u band fluxes. (nJy)"},
{"name":"u_psfFluxPercentile95", "type":"float", "doc":"Value at the 95% percentile of the u band fluxes. (nJy)"},
{"name":"u_psfFluxSigma", "type":"float", "doc":"Standard deviation of the distribution of u_psfFlux. (nJy)"},
{"name":"u_psfFluxSkew", "type":"float", "doc":"Skewness of the u band fluxes. ()"},
{"name":"u_psfFluxStetsonJ", "type":"float", "doc":"StetsonJ statistic for the u band fluxes. ()"},
{"name":"u_scienceFluxMean", "type":"float", "doc":"Weighted mean forced photometry flux for u filter. (nJy)"},
{"name":"u_scienceFluxMeanErr", "type":"float", "doc":"Standard error of u_scienceFluxMean. (nJy)"},
{"name":"u_scienceFluxSigma", "type":"float", "doc":"Standard deviation of the distribution of u_scienceFlux. (nJy)"},

{"name":"g_fpFluxMean", "type":"float", "doc":"Weighted mean forced photometry flux for g filter. (nJy)"},
{"name":"g_fpFluxMeanErr", "type":"float", "doc":"Standard error of g_fpFluxMean. (nJy)"},
{"name":"g_fpFluxSigma", "type":"float", "doc":"Standard deviation of the distribution of g_fpFlux. (nJy)"},
{"name":"g_psfFluxChi2", "type":"float", "doc":"Chi^2 statistic for the scatter of g_psfFlux around g_psfFluxMean. ()"},
{"name":"g_psfFluxErrMean", "type":"float", "doc":"Mean of the g band flux errors. (nJy)"},
{"name":"g_psfFluxLinearIntercept", "type":"float", "doc":"Linear best fit Intercept of the g band fluxes. (nJy)"},
{"name":"g_psfFluxLinearSlope", "type":"float", "doc":"Linear best fit slope of the g band fluxes. (nJy/d)"},
{"name":"g_psfFluxMAD", "type":"float", "doc":"Median absolute deviation g band fluxes. (nJy)"},
{"name":"g_psfFluxMax", "type":"float", "doc":"Maximum observed g band fluxes. (nJy)"},
{"name":"g_psfFluxMaxSlope", "type":"float", "doc":"Maximum slope between g band flux obsevations max(delta_flux/delta_time). (nJy/d)"},
#{"name":"g_psfFluxMean", "type":"float", "doc":"Weighted mean point-source model magnitude for g filter. (nJy)"},
#{"name":"g_psfFluxMeanErr", "type":"float", "doc":"Standard error of g_psfFluxMean. (nJy)"},
{"name":"g_psfFluxMin", "type":"float", "doc":"Minimum observed g band fluxes. (nJy)"},
{"name":"g_psfFluxNdata", "type":"int", "doc":"The number of data points used to compute g_psfFluxChi2. ()"},
{"name":"g_psfFluxPercentile05", "type":"float", "doc":"Value at the 5% percentile of the g band fluxes. (nJy)"},
{"name":"g_psfFluxPercentile25", "type":"float", "doc":"Value at the 25% percentile of the g band fluxes. (nJy)"},
{"name":"g_psfFluxPercentile50", "type":"float", "doc":"Value at the 50% percentile (median) of the g band fluxes. (nJy)"},
{"name":"g_psfFluxPercentile75", "type":"float", "doc":"Value at the 75% percentile of the g band fluxes. (nJy)"},
{"name":"g_psfFluxPercentile95", "type":"float", "doc":"Value at the 95% percentile of the g band fluxes. (nJy)"},
{"name":"g_psfFluxSigma", "type":"float", "doc":"Standard deviation of the distribution of g_psfFlux. (nJy)"},
{"name":"g_psfFluxSkew", "type":"float", "doc":"Skewness of the g band fluxes. ()"},
{"name":"g_psfFluxStetsonJ", "type":"float", "doc":"StetsonJ statistic for the g band fluxes. ()"},
{"name":"g_scienceFluxMean", "type":"float", "doc":"Weighted mean forced photometry flux for g filter. (nJy)"},
{"name":"g_scienceFluxMeanErr", "type":"float", "doc":"Standard error of g_scienceFluxMean. (nJy)"},
{"name":"g_scienceFluxSigma", "type":"float", "doc":"Standard deviation of the distribution of g_scienceFlux. (nJy)"},

{"name":"r_fpFluxMean", "type":"float", "doc":"Weighted mean forced photometry flux for r filter. (nJy)"},
{"name":"r_fpFluxMeanErr", "type":"float", "doc":"Standard error of r_fpFluxMean. (nJy)"},
{"name":"r_fpFluxSigma", "type":"float", "doc":"Standard deviation of the distribution of r_fpFlux. (nJy)"},
{"name":"r_psfFluxChi2", "type":"float", "doc":"Chi^2 statistic for the scatter of r_psfFlux around r_psfFluxMean. ()"},
{"name":"r_psfFluxErrMean", "type":"float", "doc":"Mean of the r band flux errors. (nJy)"},
{"name":"r_psfFluxLinearIntercept", "type":"float", "doc":"Linear best fit Intercept of the r band fluxes. (nJy)"},
{"name":"r_psfFluxLinearSlope", "type":"float", "doc":"Linear best fit slope of the r band fluxes. (nJy/d)"},
{"name":"r_psfFluxMAD", "type":"float", "doc":"Median absolute deviation r band fluxes. (nJy)"},
{"name":"r_psfFluxMax", "type":"float", "doc":"Maximum observed r band fluxes. (nJy)"},
{"name":"r_psfFluxMaxSlope", "type":"float", "doc":"Maximum slope between r band flux obsevations max(delta_flux/delta_time). (nJy/d)"},
#{"name":"r_psfFluxMean", "type":"float", "doc":"Weighted mean point-source model magnitude for r filter. (nJy)"},
#{"name":"r_psfFluxMeanErr", "type":"float", "doc":"Standard error of r_psfFluxMean. (nJy)"},
{"name":"r_psfFluxMin", "type":"float", "doc":"Minimum observed r band fluxes. (nJy)"},
{"name":"r_psfFluxNdata", "type":"int", "doc":"The number of data points used to compute r_psfFluxChi2. ()"},
{"name":"r_psfFluxPercentile05", "type":"float", "doc":"Value at the 5% percentile of the r band fluxes. (nJy)"},
{"name":"r_psfFluxPercentile25", "type":"float", "doc":"Value at the 25% percentile of the r band fluxes. (nJy)"},
{"name":"r_psfFluxPercentile50", "type":"float", "doc":"Value at the 50% percentile (median) of the r band fluxes. (nJy)"},
{"name":"r_psfFluxPercentile75", "type":"float", "doc":"Value at the 75% percentile of the r band fluxes. (nJy)"},
{"name":"r_psfFluxPercentile95", "type":"float", "doc":"Value at the 95% percentile of the r band fluxes. (nJy)"},
{"name":"r_psfFluxSigma", "type":"float", "doc":"Standard deviation of the distribution of r_psfFlux. (nJy)"},
{"name":"r_psfFluxSkew", "type":"float", "doc":"Skewness of the r band fluxes. ()"},
{"name":"r_psfFluxStetsonJ", "type":"float", "doc":"StetsonJ statistic for the r band fluxes. ()"},
{"name":"r_scienceFluxMean", "type":"float", "doc":"Weighted mean forced photometry flux for r filter. (nJy)"},
{"name":"r_scienceFluxMeanErr", "type":"float", "doc":"Standard error of r_scienceFluxMean. (nJy)"},
{"name":"r_scienceFluxSigma", "type":"float", "doc":"Standard deviation of the distribution of r_scienceFlux. (nJy)"},

{"name":"i_fpFluxMean", "type":"float", "doc":"Weighted mean forced photometry flux for i filter. (nJy)"},
{"name":"i_fpFluxMeanErr", "type":"float", "doc":"Standard error of i_fpFluxMean. (nJy)"},
{"name":"i_fpFluxSigma", "type":"float", "doc":"Standard deviation of the distribution of i_fpFlux. (nJy)"},
{"name":"i_psfFluxChi2", "type":"float", "doc":"Chi^2 statistic for the scatter of i_psfFlux around i_psfFluxMean. ()"},
{"name":"i_psfFluxErrMean", "type":"float", "doc":"Mean of the i band flux errors. (nJy)"},
{"name":"i_psfFluxLinearIntercept", "type":"float", "doc":"Linear best fit Intercept of the i band fluxes. (nJy)"},
{"name":"i_psfFluxLinearSlope", "type":"float", "doc":"Linear best fit slope of the i band fluxes. (nJy/d)"},
{"name":"i_psfFluxMAD", "type":"float", "doc":"Median absolute deviation i band fluxes. (nJy)"},
{"name":"i_psfFluxMax", "type":"float", "doc":"Maximum observed i band fluxes. (nJy)"},
{"name":"i_psfFluxMaxSlope", "type":"float", "doc":"Maximum slope between i band flux obsevations max(delta_flux/delta_time). (nJy/d)"},
#{"name":"i_psfFluxMean", "type":"float", "doc":"Weighted mean point-source model magnitude for i filter. (nJy)"},
#{"name":"i_psfFluxMeanErr", "type":"float", "doc":"Standard error of i_psfFluxMean. (nJy)"},
{"name":"i_psfFluxMin", "type":"float", "doc":"Minimum observed i band fluxes. (nJy)"},
{"name":"i_psfFluxNdata", "type":"int", "doc":"The number of data points used to compute i_psfFluxChi2. ()"},
{"name":"i_psfFluxPercentile05", "type":"float", "doc":"Value at the 5% percentile of the i band fluxes. (nJy)"},
{"name":"i_psfFluxPercentile25", "type":"float", "doc":"Value at the 25% percentile of the i band fluxes. (nJy)"},
{"name":"i_psfFluxPercentile50", "type":"float", "doc":"Value at the 50% percentile (median) of the i band fluxes. (nJy)"},
{"name":"i_psfFluxPercentile75", "type":"float", "doc":"Value at the 75% percentile of the i band fluxes. (nJy)"},
{"name":"i_psfFluxPercentile95", "type":"float", "doc":"Value at the 95% percentile of the i band fluxes. (nJy)"},
{"name":"i_psfFluxSigma", "type":"float", "doc":"Standard deviation of the distribution of i_psfFlux. (nJy)"},
{"name":"i_psfFluxSkew", "type":"float", "doc":"Skewness of the i band fluxes. ()"},
{"name":"i_psfFluxStetsonJ", "type":"float", "doc":"StetsonJ statistic for the i band fluxes. ()"},
{"name":"i_scienceFluxMean", "type":"float", "doc":"Weighted mean forced photometry flux for i filter. (nJy)"},
{"name":"i_scienceFluxMeanErr", "type":"float", "doc":"Standard error of i_scienceFluxMean. (nJy)"},
{"name":"i_scienceFluxSigma", "type":"float", "doc":"Standard deviation of the distribution of i_scienceFlux. (nJy)"},

{"name":"z_fpFluxMean", "type":"float", "doc":"Weighted mean forced photometry flux for z filter. (nJy)"},
{"name":"z_fpFluxMeanErr", "type":"float", "doc":"Standard error of z_fpFluxMean. (nJy)"},
{"name":"z_fpFluxSigma", "type":"float", "doc":"Standard deviation of the distribution of z_fpFlux. (nJy)"},
{"name":"z_psfFluxChi2", "type":"float", "doc":"Chi^2 statistic for the scatter of z_psfFlux around z_psfFluxMean. ()"},
{"name":"z_psfFluxErrMean", "type":"float", "doc":"Mean of the z band flux errors. (nJy)"},
{"name":"z_psfFluxLinearIntercept", "type":"float", "doc":"Linear best fit Intercept of the z band fluxes. (nJy)"},
{"name":"z_psfFluxLinearSlope", "type":"float", "doc":"Linear best fit slope of the z band fluxes. (nJy/d)"},
{"name":"z_psfFluxMAD", "type":"float", "doc":"Median absolute deviation z band fluxes. (nJy)"},
{"name":"z_psfFluxMax", "type":"float", "doc":"Maximum observed z band fluxes. (nJy)"},
{"name":"z_psfFluxMaxSlope", "type":"float", "doc":"Maximum slope between z band flux obsevations max(delta_flux/delta_time). (nJy/d)"},
#{"name":"z_psfFluxMean", "type":"float", "doc":"Weighted mean point-source model magnitude for z filter. (nJy)"},
#{"name":"z_psfFluxMeanErr", "type":"float", "doc":"Standard error of z_psfFluxMean. (nJy)"},
{"name":"z_psfFluxMin", "type":"float", "doc":"Minimum observed z band fluxes. (nJy)"},
{"name":"z_psfFluxNdata", "type":"int", "doc":"The number of data points used to compute z_psfFluxChi2. ()"},
{"name":"z_psfFluxPercentile05", "type":"float", "doc":"Value at the 5% percentile of the z band fluxes. (nJy)"},
{"name":"z_psfFluxPercentile25", "type":"float", "doc":"Value at the 25% percentile of the z band fluxes. (nJy)"},
{"name":"z_psfFluxPercentile50", "type":"float", "doc":"Value at the 50% percentile (median) of the z band fluxes. (nJy)"},
{"name":"z_psfFluxPercentile75", "type":"float", "doc":"Value at the 75% percentile of the z band fluxes. (nJy)"},
{"name":"z_psfFluxPercentile95", "type":"float", "doc":"Value at the 95% percentile of the z band fluxes. (nJy)"},
{"name":"z_psfFluxSigma", "type":"float", "doc":"Standard deviation of the distribution of z_psfFlux. (nJy)"},
{"name":"z_psfFluxSkew", "type":"float", "doc":"Skewness of the z band fluxes. ()"},
{"name":"z_psfFluxStetsonJ", "type":"float", "doc":"StetsonJ statistic for the z band fluxes. ()"},
{"name":"z_scienceFluxMean", "type":"float", "doc":"Weighted mean forced photometry flux for z filter. (nJy)"},
{"name":"z_scienceFluxMeanErr", "type":"float", "doc":"Standard error of z_scienceFluxMean. (nJy)"},
{"name":"z_scienceFluxSigma", "type":"float", "doc":"Standard deviation of the distribution of z_scienceFlux. (nJy)"},

{"name":"y_fpFluxMean", "type":"float", "doc":"Weighted mean forced photometry flux for y filter. (nJy)"},
{"name":"y_fpFluxMeanErr", "type":"float", "doc":"Standard error of y_fpFluxMean. (nJy)"},
{"name":"y_fpFluxSigma", "type":"float", "doc":"Standard deviation of the distribution of y_fpFlux. (nJy)"},
{"name":"y_psfFluxChi2", "type":"float", "doc":"Chi^2 statistic for the scatter of y_psfFlux around y_psfFluxMean. ()"},
{"name":"y_psfFluxErrMean", "type":"float", "doc":"Mean of the y band flux errors. (nJy)"},
{"name":"y_psfFluxLinearIntercept", "type":"float", "doc":"Linear best fit Intercept of the y band fluxes. (nJy)"},
{"name":"y_psfFluxLinearSlope", "type":"float", "doc":"Linear best fit slope of the y band fluxes. (nJy/d)"},
{"name":"y_psfFluxMAD", "type":"float", "doc":"Median absolute deviation y band fluxes. (nJy)"},
{"name":"y_psfFluxMax", "type":"float", "doc":"Maximum observed y band fluxes. (nJy)"},
{"name":"y_psfFluxMaxSlope", "type":"float", "doc":"Maximum slope between y band flux obsevations max(delta_flux/delta_time) (nJy/d)"},
#{"name":"y_psfFluxMean", "type":"float", "doc":"Weighted mean point-source model magnitude for y filter. (nJy)"},
#{"name":"y_psfFluxMeanErr", "type":"float", "doc":"Standard error of y_psfFluxMean. (nJy)"},
{"name":"y_psfFluxMin", "type":"float", "doc":"Minimum observed y band fluxes. (nJy)"},
{"name":"y_psfFluxNdata", "type":"int", "doc":"The number of data points used to compute y_psfFluxChi2. ()"},
{"name":"y_psfFluxPercentile05", "type":"float", "doc":"Value at the 5% percentile of the y band fluxes. (nJy)"},
{"name":"y_psfFluxPercentile25", "type":"float", "doc":"Value at the 25% percentile of the y band fluxes. (nJy)"},
{"name":"y_psfFluxPercentile50", "type":"float", "doc":"Value at the 50% percentile (median) of the y band fluxes. (nJy)"},
{"name":"y_psfFluxPercentile75", "type":"float", "doc":"Value at the 75% percentile of the y band fluxes. (nJy)"},
{"name":"y_psfFluxPercentile95", "type":"float", "doc":"Value at the 95% percentile of the y band fluxes. (nJy)"},
{"name":"y_psfFluxSigma", "type":"float", "doc":"Standard deviation of the distribution of y_psfFlux. (nJy)"},
{"name":"y_psfFluxSkew", "type":"float", "doc":"Skewness of the y band fluxes. ()"},
{"name":"y_psfFluxStetsonJ", "type":"float", "doc":"StetsonJ statistic for the y band fluxes. ()"},
{"name":"y_scienceFluxMean", "type":"float", "doc":"Weighted mean forced photometry flux for y filter. (nJy)"},
{"name":"y_scienceFluxMeanErr", "type":"float", "doc":"Standard error of y_scienceFluxMean. (nJy)"},
{"name":"y_scienceFluxSigma", "type":"float", "doc":"Standard deviation of the distribution of y_scienceFlux. (nJy)"},
  ],
  "indexes": [
    "PRIMARY KEY (diaObjectId)",
    "KEY htmid16idx (htm16)",
    "KEY idxMaxTai (maxTai)"
  ]
}
if __name__ == "__main__":
    print('<h2>Fields of the Lasair Object Schema</h2>')
    print('<h3>Core Attributes</h3>')
    print('<table border=1>')
    for f in schema['fields']:
        if 'section' in f:
            print('</table>')
            print('<p><b>%s</b>: %s' % (f['section'], f['doc']))
            print('<table border=1>')
        elif 'name' in f:
            print('<tr><td><tt>%s</tt></td><td>%s</td>' % (f['name'], f['doc']))
    print('</table>')

    print('<h3>Extended Attributes</h3><table>')
    print('<table border=1>')
    for f in schema['ext_fields']:
       if 'name' in f:
            print('<tr><td><tt>%s</tt></td><td>%s</td>' % (f['name'], f['doc']))
    print('</table>')
