# Generated by Django 5.2.1 on 2026-05-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MmaWatchmap',
            fields=[
                ('mw_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_tai', models.FloatField()),
                ('event_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('mocimage', models.TextField(blank=True, null=True)),
                ('area10', models.FloatField()),
                ('area50', models.FloatField()),
                ('area90', models.FloatField()),
                ('namespace', models.CharField(blank=True, max_length=16, null=True)),
                ('otherId', models.CharField(blank=True, max_length=256, null=True)),
                ('version', models.CharField(blank=True, max_length=256, null=True)),
                ('more_info', models.CharField(blank=True, max_length=1024, null=True)),
                ('params', models.JSONField()),
            ],
            options={
                'db_table': 'mma_areas',
                'managed': True,
            },
        ),
    ]
