---
# tasks file for lasair-database

- name: Setup Lasair database
  community.mysql.mysql_query:
    query:
      - CREATE DATABASE IF NOT EXISTS {{ mysql_db_name }};
      - USE {{ mysql_db_name }};
      - CREATE USER IF NOT EXISTS '{{ mysql_db_user }}'@'localhost' IDENTIFIED BY '{{ mysql_db_password }}';
      - CREATE USER IF NOT EXISTS '{{ mysql_db_user }}'@'%' IDENTIFIED BY '{{ mysql_db_password }}';
      - GRANT ALL PRIVILEGES ON {{ mysql_db_name }}.* TO '{{ mysql_db_user }}'@'localhost';
      - GRANT ALL PRIVILEGES ON {{ mysql_db_name }}.* TO '{{ mysql_db_user }}'@'%';
      - GRANT FILE ON *.* TO '{{ mysql_db_user }}'@'localhost';
      - GRANT FILE ON *.* TO '{{ mysql_db_user }}'@'%';
      - CREATE USER IF NOT EXISTS '{{ msql_db_user_readonly }}'@'localhost' IDENTIFIED BY '{{ mysql_db_password_readonly }}';
      - CREATE USER IF NOT EXISTS '{{ msql_db_user_readonly }}'@'%' IDENTIFIED BY '{{ mysql_db_password_readonly }}';
      - GRANT SELECT ON {{ mysql_db_name }}.* TO '{{ msql_db_user_readonly }}'@'%';
      - DROP FUNCTION IF EXISTS tainow;
      - CREATE FUNCTION tainow () RETURNS DOUBLE DETERMINISTIC RETURN (unix_timestamp(now())/86400 + 40587);
      - GRANT EXECUTE ON FUNCTION {{ mysql_db_name }}.tainow TO '{{ msql_db_user_readonly }}'@'%';
    login_host: 127.0.0.1
    login_user: root
    login_password: "{{ mysql_root_password }}"
    single_transaction: yes

- name: Create SQL files
  ansible.builtin.shell:
    cmd: "python3 3_make_create_table.py sql {{ schema }} {{ item }} > {{ item }}.sql"
    chdir: 


- name: Create tables
  community.mysql.mysql_query:
    query: "{{ lookup('file', '../common/schema/' + schema + '/' + item, split_lines=false) }}"
    login_host: 127.0.0.1
    login_user: "{{ mysql_db_user }}"
    login_password: "{{ mysql_db_password }}"
    login_db: "{{ mysql_db_name }}"
    single_transaction: yes
  with_items:
    - "objects.sql"
    - "sherlock_classifications.sql"
    - "crossmatch_tns.sql"
    - "area_hits.sql"
    - "watchlist_hits.sql"
    - "annotations.sql"
    - "mma_area_hits.sql"
    - "lasair_statistics.sql"
    #- "/common/schema/lasair_sql/ssObjects.sql"

