---

- name: Check if volume exists
  stat:
    path: /dev/vdb
  register: sdb

- name: Create filesystem for Sherlock database
  become: true
  community.general.filesystem:
    fstype: ext4
    dev: /dev/vdb
  when: sdb.stat.exists

- name: Ensure data filesystem is mounted
  become: true
  ansible.posix.mount:
    path: /var/lib/mysql
    src: /dev/vdb
    fstype: ext4
    opts: nofail
    state: mounted
  when: sdb.stat.exists

