---
# tasks file for sherlock

- import_tasks: filesystem.yml

- name: Include mariadb role
  ansible.builtin.include_role:
    name: gkansible.gkservercollection.mariadb

- name: Include mysql_sherlock role
  ansible.builtin.include_role:
    name: gkansible.gkservercollection.mysql_sherlock

- import_tasks: database.yml
- import_tasks: wrapper.yml
- import_tasks: service.yml

