---

- name: "Create /opt/lasair directory"
  become: true
  file:
    path: /opt/lasair
    state: directory
    owner: "{{ ansible_user_id }}"

- name: "Deploy service config"
  template:
    src:  service_settings.yaml.j2
    dest: /opt/lasair/sherlock_service_settings.yaml

- name: Link Sherlock settings file
  become: true
  file:
    src: "{{ ansible_env.HOME }}/{{ git_name }}/pipeline/sherlock/sherlock_settings.yaml"
    dest:  /opt/lasair/sherlock_settings.yaml
    state: link

- name: "Install apt packages"
  become: true
  apt:
    name:
      - gcc
      - g++
      - python3
      - python3-venv
      - python3-dev
      - python3-yaml
      - python3-pip
      - python3-flask
      - nginx
      - uwsgi
      - uwsgi-plugin-python3
      - flask-restful
      - python3-numpy
      - python3-setuptools
      - python3-wheel
      - python3-packaging

- name: "Install pip packages"
  pip:
    virtualenv: "{{ venv_path }}"
    virtualenv_site_packages: true
    virtualenv_command: 'python3 -m venv'
    extra_args: "--no-use-pep517"
    name: 
      - qub-sherlock==2.3.1

- name: "Copy app.py"
  get_url:
    url: "https://raw.githubusercontent.com/lsst-uk/{{ git_name}}/{{ lasair_version }}/services/sherlock/app.py"
    dest: /opt/lasair/app.py
    mode: 0644

- name: "Create uwsgi ini file"
  template:
    src:  sherlock_service.ini.j2
    dest: /opt/lasair/sherlock_service.ini

- name: Create systemd service file
  become: true
  copy:
    src: sherlocksvc.service
    dest: /etc/systemd/system/sherlocksvc.service

- name: Make sure service unit is running
  become: true
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: sherlocksvc

- name: Create nginx site file
  become: true
  copy:
    src: sherlocksvc.nginx
    dest: /etc/nginx/sites-available/sherlocksvc

- name: Link nginx site file
  become: true
  file:
    src: /etc/nginx/sites-available/sherlocksvc
    dest:  /etc/nginx/sites-enabled/sherlocksvc
    state: link

- name: Unlink default nginx site file
  become: true
  file:
    path:  /etc/nginx/sites-enabled/default
    state: absent

# could make this a handler
- name: Restart sherlocksvc
  become: true
  ansible.builtin.systemd:
    name: sherlocksvc.service
    state: restarted

# could make this a handler
- name: Restart nginx
  become: true
  ansible.builtin.systemd:
    name: nginx.service
    state: restarted

