---

- name: Install apt packages
  become: yes
  ansible.builtin.apt:
      name:
        - python3-pip
      state: present
      update_cache: true

- name: "Install pip packages"
  pip:
    name:
      - confluent-kafka
      - multiprocessing-logging
    extra_args: "--break-system-packages"

- name: Make sure the repo is up to date
  git:
    repo: "{{ git_url }}"
    dest: "{{ ansible_env.HOME }}/{{ git_name }}"
    version: "{{ lasair_version }}"

- name: Creates directory for logs
  file:
    path: "{{ ansible_env.HOME }}/logs"
    state: directory

- name: "Deploy Sherlock config"
  template:
    src:  sherlock_settings.yaml.j2
    dest: "{{ ansible_env.HOME }}/{{ git_name }}/pipeline/sherlock/sherlock_settings.yaml"

- name: "Deploy Sherlock wrapper config"
  template:
    src:  sherlock_wrapper_config.yaml.j2
    dest: "{{ ansible_env.HOME }}/{{ git_name }}/pipeline/sherlock/wrapper_config.yaml"

- name: "Deploy Sherlock wrapper runner config"
  template:
    src:  sherlock_wrapper_runner.json.j2
    dest: "{{ ansible_env.HOME }}/{{ git_name }}/pipeline/sherlock/wrapper_runner.json"

- name: Create lasair-sherlock systemd service file
  become: true
  template:
    src: lasair-sherlock.service
    dest: /etc/systemd/system/lasair-sherlock.service

- name: Make sure lasair-sherlock is running
  become: true
  ansible.builtin.systemd:
    state: started
    enabled: true
    #state: stopped
    #enabled: false
    name: lasair-sherlock

