"""
Dummy settings file for tests
"""

MAX_STATEMENT_TIME      = 20
KAFKA_GROUPID = "blah"
KAFKA_MAXALERTS = 1
DB_USER_READWRITE = ''
DB_PASS_READWRITE = ''
DB_PORT = 8888
DB_HOST = ''
SLACK_URL = ''
WAIT_TIME = 0
