# Playbook for deploying standalone cassandra clusters

---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Get current git branch
      ansible.builtin.command: git branch --show-current
      register: git_tag
  tags: always

- hosts: all
  gather_facts: true
  vars_files:
    - settings.yaml
  tasks:
    - name: Set Lasair version
      ansible.builtin.set_fact:
        lasair_version: "{{ hostvars['localhost']['git_tag'].stdout }}"
    - name: Get vault settings
      ansible.builtin.set_fact:
        settings: "{{ lookup('hashi_vault', 'secret='+vault.path+'/settings url='+vault.url)}}"
  tags:  
    - always

- hosts: cassandranodes, cutoutcass
  gather_facts: true
  tags: always

- hosts: cassandranodes, cutoutcass
  gather_facts: false
  become: yes
  tasks:
    - name: create filesystems
      community.general.filesystem:
        fstype: ext4
        dev: "{{ item }}"
      loop:
        - /dev/vdb
        - /dev/vdc
    - name: ensure commitlog filesystem is mounted
      ansible.posix.mount:
        path: /var/lib/cassandra-commitlog
        src: /dev/vdb
        fstype: ext4
        opts: nofail
        state: mounted
    - name: ensure data filesystem is mounted
      ansible.posix.mount:
        path: /var/lib/cassandra
        src: /dev/vdc
        fstype: ext4
        opts: nofail
        state: mounted
  tags: filesystem

- hosts: cassandranodes
  gather_facts: false
  vars_files:
    - settings.yaml
    - cassandra_mapping.yaml
  vars:
    cassandra_cluster_name: "{{ group_names[0] }}"
    cassandra_commitlog_dir: /var/lib/cassandra-commitlog
  roles:
    - gkansible.gkservercollection.cassandra4
  tags: cassandra

- hosts: cutoutcass
  gather_facts: false
  vars_files:
    - settings.yaml
    - cassandra_mapping.yaml
  vars:
    cassandra_cluster_name: "{{ group_names[0] }}"
    cassandra_commitlog_dir: /var/lib/cassandra-commitlog
  roles:
    - gkansible.gkservercollection.cassandra4
  tags: cassandra


- hosts: cassandranodes, cutoutcass
  vars_files:
    - settings.yaml
  vars:
    cassandra_cluster_name: "{{ group_names[0] }}"
  roles:
    - gkansible.gkservercollection.cassandra_start_service
  serial: 1
  tags: cassandra

# Hopefully temporary workaround for incompatibility between current version of Cassandra and Python 3.12 - 3/6/25
- hosts: cassandranodes, cutoutcass
  gather_facts: false
  become: yes
  tasks:
    - name: Remove default cqlsh
      ansible.builtin.file:
        path: /usr/bin/cqlsh
        state: absent
    - name: Install cqlsh snap
      shell: "sudo snap install cqlsh --devmode"
  tags: cassandra, cutoutcass

- hosts: cassandranodes[0]
  vars_files:
    - settings.yaml
  vars:
    schema: 7_4_A
  roles:
    - lasair_cassandra
  tags: cassandra

- hosts: cutoutcass[0]
  vars_files:
    - settings.yaml
  vars:
    schema: 7_4_A
  roles:
    - lasair_cutoutcass
  tags: cutoutcass

