---
- hosts: localhost
  gather_facts: true
  tasks:
    - name: ensure os config dir exists
      ansible.builtin.file:
        path: ~/.config/openstack
        state: directory
    - name: create clouds.yml
      ansible.builtin.template:
        src: clouds.yml.j2
        dest: ~/.config/openstack/clouds.yml

- name: create ssh keypair 
  import_playbook: keypair.yaml

- name: deploy infrastructure using terraform
  import_playbook: infra.yaml

- name: re-run cloud-init to fix network interfaces
  import_playbook: cloud-init.yaml

