---
- name: "Set apt-daily time"
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/system/timers.target.wants/apt-daily.timer
    regexp: '^OnCalendar='
    line: "OnCalendar=*-*-* {{ apt_daily_time }}"
  notify:
    - Reload units

- name: "Set apt-daily delay"
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/system/timers.target.wants/apt-daily.timer
    regexp: '^RandomizedDelaySec='
    line: "RandomizedDelaySec=2h"
  notify:
    - Reload units

- name: "Set apt-daily-upgrade time"
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/system/timers.target.wants/apt-daily-upgrade.timer
    regexp: '^OnCalendar='
    line: "OnCalendar=*-*-* {{ apt_daily_upgrade_time }}"
  notify:
    - Reload units

- name: "Set apt-daily-upgrade delay"
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/system/timers.target.wants/apt-daily-upgrade.timer
    regexp: '^RandomizedDelaySec='
    line: "RandomizedDelaySec=45m"
  notify:
    - Reload units

