---

- name: "Create data directory"
  become: true
  file:
    path: "{{ data_fs.path }}/kafka"
    state: directory
    mode: 0777

- name: "Deploy Kafka compose file"
  template:
    src:  kafka-compose.yaml.j2
    dest: kafka-compose.yml
  vars:
    mntpath: "{{ data_fs.path }}/kafka"
    logpath: "{{ data_fs.path }}/kafka"

- name: "Start Kafka services"
  become: true
  docker_compose:
    project_src:
        '.'
    files:
      - kafka-compose.yml
    services:
      - kafka
    state:
      present
