---

- name: "Install packages"
  become: true
  apt:
    pkg:
      - python3-pip
      - swig
      - zlib1g
    state: present
    update-cache: true

- name: "Install python packages"
  become: true
  pip:
    virtualenv: "{{ venv_path }}"
    virtualenv_site_packages: true
    name:
      - confluent-kafka
      - confluent_kafka[schemaregistry,avro]
      - fastavro
      - gkhtm
      - cassandra-driver
      - gkutils
      - gkdbutils
      - docopt
      - mysql-connector-python
      - lz4

- name: Make sure the repo is up to date
  git: 
    repo: "{{ git_url }}"
    dest: "{{ ansible_env.HOME }}/{{ git_name }}"
    version: "{{ lasair_version }}"

- name: Create logs directory
  file:
    path: "{{ ansible_env.HOME }}/logs"
    state: directory

