SCHEMA_REG_URL = "https://usdf-alert-schemas-dev.slac.stanford.edu"
SCHEMA = '../../../../common/schema/dp02.avsc'
SCHEMA_VERSION = '11_0'
CASSANDRA_HEAD = ''
KAFKA_SERVER=''
WAIT_TIME=60
SLACK_URL=''
SLACK_CHANNEL=''
KAFKA_GROUPID=''
N_DIASOURCES_DB=4
