---
- name: "Ensure Python installed"
  become: true
  ansible.builtin.apt:
    pkg:
      - python3
      - python3-pip
      - python3-venv
    state: present
    update-cache: yes

- name: "Set up Python virtual environment"
  become: true
  ansible.builtin.command: "python3 -m venv --system-site-packages {{ venv_path }}"
  creates: "{{ venv_path }}"

