CREATE TABLE IF NOT EXISTS objects(
`diaObjectId` bigint NOT NULL,
`ra` double,
`decl` double,
`pmRa` float,
`pmDec` float,
`lastDiaSourceMJD` double,
`firstDiaSourceMJD` double,
`u_psfFlux` float,
`u_psfFluxMean` float,
`u_psfFluxMeanErr` float,
`g_psfFlux` float,
`g_psfFluxMean` float,
`g_psfFluxMeanErr` float,
`r_psfFlux` float,
`r_psfFluxMean` float,
`r_psfFluxMeanErr` float,
`i_psfFlux` float,
`i_psfFluxMean` float,
`i_psfFluxMeanErr` float,
`z_psfFlux` float,
`z_psfFluxMean` float,
`z_psfFluxMeanErr` float,
`y_psfFlux` float,
`y_psfFluxMean` float,
`y_psfFluxMeanErr` float,
`nSources` int NOT NULL,
`nuSources` int,
`ngSources` int,
`nrSources` int,
`niSources` int,
`nzSources` int,
`nySources` int,
`tns_name` varchar(16),
`nearbyObj1` bigint,
`nearbyObj1Dist` float,
`nearbyObj1LnP` float,
`absMag` float,
`absMagMJD` float,
`BBBRiseRate` float,
`BBBFallRate` float,
`BBBTemp` float,
`BBBPeakFlux` float,
`BBBPeakMJD` float,
`BBBPeakAbsMag` float,
`glat` float,
`ebv` float,
`jumpFromMean20` float,
`latestPairMJD` float,
`latestPairColourMag` float,
`latestPairColourBands` varchar(16),
`latestPairColourTemp` float,
`penultimatePairMJD` float,
`penultimatePairColourMag` float,
`penultimatePairColourBands` varchar(16),
`penultimate_pairColourTemp` float,
`htm16` bigint NOT NULL,
`timestamp` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (diaObjectId),
KEY htmid16idx (htm16),
KEY idxMaxTai (lastDiaSourceMJD)
)
