CREATE TABLE IF NOT EXISTS objects(
`diaObjectId` bigint NOT NULL,
`htm16` bigint NOT NULL,
`ra` double,
`decl` double,
`nDiaSources` int,
`gPSFluxMax` float,
`gPSFluxMean` float,
`gPSFluxMaxSlope` float,
`gPSFluxNdata` int,
`rPSFluxMax` float,
`rPSFluxMean` float,
`rPSFluxMaxSlope` float,
`rPSFluxNdata` int,
`maxTai` double,
`minTai` double,
`uPSFlux` float,
`gPSFlux` float,
`rPSFlux` float,
`iPSFlux` float,
`zPSFlux` float,
`yPSFlux` float,
`absFlux` float,
`fluxJump` float,
`uExpRate` float,
`gExpRate` float,
`rExpRate` float,
`iExpRate` float,
`zExpRate` float,
`yExpRate` float,
`uExpRateErr` float,
`gExpRateErr` float,
`rExpRateErr` float,
`iExpRateErr` float,
`zExpRateErr` float,
`yExpRateErr` float,
`bazinExpRiseRate` float,
`bazinExpFallRate` float,
`bazinExpTemp` float,
`bazinExpRiseRateErr` float,
`bazinExpFallRateErr` float,
`bazinExpTempErr` float,
PRIMARY KEY (diaObjectId),
KEY htmid16idx (htm16),
KEY idxMaxTai (maxTai)
)
