---

# Set up filter as a systemd service

- name: Create systemd service file
  become: true
  template:
    src: filter.service
    dest: /etc/systemd/system/lasair-filter.service

- name: Make sure a service unit is running
  become: true
  ansible.builtin.systemd:
    #state: started
    #enabled: true
    state: stopped
    enabled: false
    name: lasair-filter 

