---
# tasks file for roles/lasair_service

- name: Install packages
  become: yes
  apt:
      name: 
        - swig
        - python3-dev
        - python3-pip
        - mariadb-client
      state: present
      update_cache: true

- name: Install python packages
  become: yes
  pip:
      executable: pip3
      name:
        - docopt
        - numpy
        - requests
        - mysql-connector-python

- name: Install more python packages
  become: yes
  pip:
      executable: pip3
      name:
        - gkhtm
        - gkutils
        - mocpy
        - fink-client
        - lasair
        - hmpty

- name: Make sure the repo is up to date
  git: 
      repo: "{{ git_url }}"
      dest: "{{ ansible_env.HOME }}/{{ git_name }}"
      version: "{{ lasair_version }}"

- import_tasks: cron.yml
- import_tasks: settings.yml
