---
# tasks file for roles/lasair_service

- name: Install packages
  become: yes
  apt:
      name: 
        - swig
        - python3-dev
        - python3-pip
        - mariadb-client
        - python3-setuptools
        - python3-wheel
        - python3-packaging
      state: present
      update_cache: true

- name: Install python packages
  become: yes
  pip:
    virtualenv: "{{ venv_path }}"
    virtualenv_site_packages: true
    executable: pip3
    name:
      - docopt
      - numpy
      - requests
      - mysql-connector-python
      - gkhtm
      - gkutils
      - mocpy
      - fink-client
      - lasair
      - skytag

- name: Install more python packages
  become: yes
  pip:
    virtualenv: "{{ venv_path }}"
    virtualenv_site_packages: true
    executable: pip3
    name:
      - hmpty
    extra_args: "--no-use-pep-517"

- name: Make sure the repo is up to date
  git: 
      repo: "{{ git_url }}"
      dest: "{{ ansible_env.HOME }}/{{ git_name }}"
      version: "{{ lasair_version }}"

- import_tasks: cron.yml
- import_tasks: settings.yml
